bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path

from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.ImageCreateView.as_view(), name='create'),
    path('detail/<int:id>/<slug:slug>/', views.ImageDetail.as_view(), name='detail'),
    # Ajax request
    path('like/', views.ImageLike.as_view(), name='like'),
]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.http import HttpResponse
from django.urls import reverse


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Image, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

    def __str__(self):
        return self.title

images/forms.py
from urllib import request

from django.core.files.base import ContentFile
from django.utils.text import slugify
from django import forms

from .models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {'url': forms.HiddenInput}

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpeg', 'jpg']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions.')
        return url

    def save(self, force_insert=True, force_update=True, commit=True):
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title), image_url.rsplit('.', 1)[1].lower())
        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()), save=False)
        if commit:
            image.save()
        return image

images/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.views.generic import View, DetailView
from django.http import JsonResponse

from .forms import ImageCreateForm
from .models import Image


@method_decorator(login_required, name='dispatch')
class ImageCreateView(View):
    template_name = 'images/image/create.html'

    def get(self, request):
        form = ImageCreateForm(data=request.GET)
        return render(request, self.template_name, {'section': 'images', 'form': form})

    def post(self, request):
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            messages.success(request, 'Image added successfully')
            return redirect(new_item.get_absolute_url())
        return render(request, self.template_name, {'section': 'images', 'form': form})


class ImageDetail(DetailView):
    model = Image
    template_name = 'images/image/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['section'] = 'images'
        return context


class ImageLike(View):
    @method_decorator(login_required, name='dispatch')
    def post(self, request):
        image_id = request.POST.get('id')
        action = request.POST.get('action')
        if image_id and action:
            try:
                image = Image.objects.get(id=image_id)
                if action == 'like':
                    image.users_like.add(request.user)
                else:
                    image.users_like.remove(request.user)
                return JsonResponse({'status': 'ok'})
            except Image.DoesNotExist:
                pass
        return JsonResponse({'status': 'ko'})

images/templates/images/image/create.html
{% extends 'base.html' %}

{% block title %}bookmark an image{% endblock %}

{% block content %}
	<h1>Bookmark an image</h1>
	<img src="{{ request.GET.url }}" class="image-preview">
	<form action="." method="post">
		{{ form.as_p }}
		{% csrf_token %}
		<input type="submit" value="Bookmark it!">
	</form>
{% endblock %}

images/templates/images/image/detail.html
{% extends 'base.html' %}


{% block title %}{{ image.title }}{% endblock %}

{% block content %}
	<h1>{{ image.title }}</h1>
	{% load thumbnail %}
	{% thumbnail image.image "300" as im %}
	<a href="{{ image.image.url }}">
		<img src="{{ im.url }}" class="image-detail">
	</a>
	{% endthumbnail %}
	{% with total_likes=image.users_like.count  users_like=image.users_like.all %}

		<div class="image-info">
			<div>
				<span class="count">
					<span class="total">{{ total_likes }}</span>
					like{{ total_likes|pluralize }}
				</span>
				<a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
					{% if request.user not in users_like %}
						Like
					{% else %}
						Unlike
					{% endif %}
				</a>
			</div>
		{{ image.description|linebreaks }}
		</div>
		<div class="image-like">
			{% for user in image.users_like.all %}
				<div>
					<img src="{{ user.profile.photo.url }}">
					<p>{{ user.first_name }}</p>
				</div>
			{% empty %}
				Nobody likes this image yet.
			{% endfor %}
		</div>
	{% endwith %}
{% endblock %}

{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "images:like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');

          // toggle data-action
          $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
          // toggle link text
          $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

          // update total likes
          var previous_likes = parseInt($('span.count .total').text());
          $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
        }
      }
    );
  });
{% endblock %}